### ISSUE TITLE
How to do inference?

### ISSUE THREAD

**Issue by m41w4r3exe** [Sound2Synth/Sound2Synth#3]
Thank you for sharing your work, much appreciated!

However I could not find how to do inference, even after diving into the code.

I downloaded spec checkpoints from Google Drive (through Dropbox), but there are no args.json file.

also I am not sure it is the multimodal model since it says 'spec', to my understanding there should be a backbone and a classifier model? it seems like ensemble.sh file should have a list of them but it is empty?

I would love to try it out as it looks very promising.

**Comment by MircoBerlin** [comment]
@Magolor @JingYansen @yuancc06  I have the same problem. It seems I got the server running since I can ping it with Dexed and can see a log entry in my console anyway, it doesn't seems to generate a new preset.

Then like @m41w4r3exe said I get an error about missing  args.json file.

What is missing here? The .ckpt files on Drive doesnt seem to be all that we need thank you

**Comment by Magolor** [comment]
`args.json` is basically the config for training the model, so most of it is not used. The config is shown in the `manager.py`:
```python
    args = HeavenArguments.from_parser([
        IntArgumentDescriptor("algorithm",default=0),
        StrArgumentDescriptor("server",default=get_config('server_root')),
        StrArgumentDescriptor("data-server",short='ds',default=get_config('server_root')),
        LiteralArgumentDescriptor("split",short="sp",choices=['large','aug','rand','aug-rand'],default='large'),
        LiteralArgumentDescriptor("backbone",choices=['spec','multi','multi-spec'],default='spec'),
        LiteralArgumentDescriptor("classifier",choices=['parameter','oscillator'],default='parameter'),
        StrArgumentDescriptor("exp-info",short='info',default=None),
        FloatArgumentDescriptor("limit_train_batches", short="limtr", default=1.0),
        FloatArgumentDescriptor("limit_val_batches", short="limvl", default=1.0),
        SwitchArgumentDescriptor("sync-data",short='syncd'),
        SwitchArgumentDescriptor("monitor"),
        SwitchArgumentDescriptor("no-metric",short="nom"),
        SwitchArgumentDescriptor("add-to-ensemble",short="add"),
        SwitchArgumentDescriptor("back-sync",short="backs"),
        SwitchArgumentDescriptor("clear",short="clr"),
        StrArgumentDescriptor("conda-env",short="conda",default="source /home/<USERNAME>/miniconda3/bin/activate; conda activate base"),
        # StrArgumentDescriptor("conda-env",short="conda",default="conda activate py38"),
        StrArgumentDescriptor("cuda", short="cd", default="0"),
    ])
```

This is just like the argparse with a wrapper, eventually you get a JSON containing these keys.

The tricky key is probably the `train_args`. It seems only `synth`, `backbone`, `classifier`, and `dataset_type` are used in inference.
The `synth` we are using is `Dexed` only. The `backbone` is `multimodal` for our multimodal checkpoints. The `classifier` is `parameter`. And the `dataset_type` is `multimodal` for our multimodal checkpoints.
These parameters can be looked up in `interface/__init__.py`, `model/__init__.py` and `dataset/__init__.py` separately.

So in a nut shell, I think a config file like:
```json
{
    "train_args": {
        "synth": "Dexed",
        "backbone": "multimodal",
        "classifier": "parameter",
        "dataset_type": "multimodal"
    }
}
```
is probably sufficient.

**Comment by MircoBerlin** [comment]
@Magolor thanks for the hints.

I am somewhat a bit further but still get a lot of mess:

`torch.Size([1, 192819])
torch.Size([377, 1025])
dict_keys(['main', 'mel', 'mfcc', 'spec_amp', 'mel_amp', 'spec_rms', 'mel_rms', 'zcr', 'rms', 'flatness', 'chroma'])
Unhandled Exception: output_dim cannot be None or 0, it must be a valid integer greater than 0
Traceback (most recent call last):
  File "/Users/music/PycharmProjects/Sound2Synth-2/server/server.py", line 43, in index
    preset = Sound2Synth(filepath, app.config['MODEL_ENSEMBLE'])
  File "/Users/music/PycharmProjects/Sound2Synth-2/server/app.py", line 63, in Sound2Synth
    model = LoadModel(experiment); pred = model(input_tensor)
  File "/Users/music/PycharmProjects/Sound2Synth-2/server/app.py", line 15, in LoadModel
    backbone = get_backbone(train_args.backbone, train_args),
  File "/Users/music/PycharmProjects/Sound2Synth-2/./model/__init__.py", line 30, in get_backbone
    backbone = MultimodalBackbone(output_dim=feature_dim,mode_dropout=args.mode_dropout,conv=args.multimodal_use_spec)
  File "/Users/music/PycharmProjects/Sound2Synth-2/./model/multimodal_backbone.py", line 43, in __init__
    raise ValueError(f"output_dim cannot be None or 0, it must be a valid integer greater than 0")
ValueError: output_dim cannot be None or 0, it must be a valid integer greater than 0
127.0.0.1 - - [17/Nov/2024 17:31:00] "POST / HTTP/1.1" 500 -

`

Any ideas? Thanks!

**Comment by Magolor** [comment]
This means the `feature_dim` argument is required in the `train_args`. All similar arguments are in `train.py` or `test.py`, with default values. In this case, `feature_dim` should be 2048.

**Comment by MircoBerlin** [comment]
got it! Will try it and will let you know! thanks @Magolor

**Comment by DBraun** [comment]
Could someone suggest a way to *create* a .SYX file from Sound2Synth without using any of the Tracktion or PyAU code? I have a good script for parsing syx files into a CSV format (https://github.com/DBraun/DX7-JAX/blob/main/parse_dx7.py) I think it could be adapted for producing SYX files from Sound2Synth, but I'm having some trouble running inference and mapping the output.

**Comment by DBraun** [comment]
I'm still trying to do inference but am confused. I'm looking at https://github.com/Sound2Synth/Sound2Synth/blob/main/interface/dexed.py

What is the correct `REG_NCLASS` value for the provided checkpoints? The current code uses 64, and the checkpoint output dimension from the `spec_latest` is 6557. With 1077 classification parameters `sum([pair[1] for pair in classification_parameters])` and 87 regression parameters, I calculate:
  - 64 × 87 + 1077 = 6645 (off by 88)
  - 63 × 87 + 1077 = 6558 (off by 1)

If `REG_NCLASS` is 64, does the model output 88 extra numbers that aren't used by `from_tensor()`?

**Comment by JingYansen** [comment]
@DBraun Sorry for the confusion! The checkpoint we upload indeed doesn't match the version if the code. We are still trying to find the right checkpoint file from the server we use three years ago. You can also train a new model using the json files we published.

**Comment by JingYansen** [comment]
@DBraun Also, if you want to use the current checkpoints we uploaded, you can check the commit 69ca406. In this commit we change the original 94 continuous parameters and 59 discrete parameters (this corresponds to the checkpoints we uploaded), into 87 continuous and 66 discrete parameters (this corresponds to the setting in our newest commit and the paper). You can change the interface/dexed.py from the current commit into the version before 69ca406, and this will solve your problem~
The reason for such changes is that we mistakenly set the parameters OSC KEY SYNC, BREAK POINT and P MOD SENS into continuous parameters, but they actually are discrete ones. This mistake do not have much influence on the performance of the model, because we actually use 64-way classifications with label-smoothing to learn the continuous parameters. OSC KEY SYNC is a 2 classes parameter. P MOD SENS is an 8 classes paramter. So the 64 classes can cover those classes. BREAK POINT have 88 classes, which is greater than 64 classes, but this minor difference will have very little difference to the final result :）

<img width="2295" height="1318" alt="Image" src="https://github.com/user-attachments/assets/a50a2fec-4df4-4ec0-9e17-7c0f1f202702" />

**Comment by DBraun** [comment]
Thanks I’ll give this a try today!

**Comment by DBraun** [comment]
Here's my branch where I can do inference and generate SYX files with the prior commit and checkpoints.

https://github.com/DBraun/Sound2Synth/tree/inference

I had to change `n_mfcc` to 20. I also assume the algorithm for the checkpoint is 0 (from 0 to 31). In Dexed some of the audio is plausible, but most of it is bad, indicating something is wrong with my approach. This is true even if I assume a different algorithm was used. `06 ground truth.wav` sounds like a disconnected phone call with a steady rhythm. If you rename `sound2synth_algo00.syx.txt` to `sound2synth_algo00.syx` and then listen to the preset named `6. 05_A00`, it has the same rhythm but the timbre is very different from `06 model prediction.wav`. Do you think you could use your Dexed server to save the prediction for  `06 ground truth.wav` to a SYX file and then upload it here? Then I will compare the two SYX files to hunt down the issue in my SYX generation or the inference code.

[sound2synth_algo00.syx.txt](https://github.com/user-attachments/files/21500121/sound2synth_algo00.syx.txt)

**Comment by JingYansen** [comment]
@DBraun Thank you for your work! But unfortunately after four years since we implemented this work, we cannot find the right checkpoint at this moment. Maybe you can retrain the model using our published dataset?
